# Generated by Django 5.0.6 on 2025-04-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alluser',
            name='occupation',
            field=models.CharField(choices=[('investor', 'Investor'), ('investment_finder', 'Investment Finder'), ('partnership', 'Partnership'), ('others', 'Others')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='alluser',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
    ]
